//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.01 at 04:51:01 PM EDT 
//

package com.alphasystem.morphologicalanalysis.morphology.model.support;

import com.alphasystem.arabic.model.ArabicWord;

import static com.alphasystem.arabic.model.ArabicLetterType.*;
import static com.alphasystem.arabic.model.ArabicWord.getWord;

/**
 * @author sali
 */
public enum SarfTermType {

    PAST_TENSE(getWord(FA, AIN, LAM, SPACE, MEEM, ALIF, DDAD, YA)),

    PRESENT_TENSE(getWord(FA, AIN, LAM, SPACE, MEEM, DDAD, ALIF, RA, AIN)),

    VERBAL_NOUN(getWord(MEEM, SAD, DAL, RA)),

    ACTIVE_PARTICIPLE_MASCULINE(getWord(ALIF_HAMZA_BELOW, SEEN, MEEM, SPACE,
            FA, ALIF, AIN, LAM, SPACE, MEEM, THAL, KAF, RA)),

    ACTIVE_PARTICIPLE_FEMININE(getWord(ALIF_HAMZA_BELOW, SEEN, MEEM, SPACE, FA,
            ALIF, AIN, LAM, SPACE, MEEM, WAW_HAMZA_ABOVE, NOON, THA)),

    PAST_PASSIVE_TENSE(getWord(FA, AIN, LAM, SPACE, MEEM, ALIF, DDAD, YA,
            SPACE, MEEM, BA, NOON, YA, SPACE, AIN, LAM, ALIF_MAKSURA, SPACE,
            ALIF, LAM, MEEM, JEEM, HA, WAW, LAM)),

    PRESENT_PASSIVE_TENSE(getWord(FA, AIN, LAM, SPACE, MEEM, DDAD, ALIF, RA,
            AIN, SPACE, MEEM, BA, NOON, YA, SPACE, AIN, LAM, ALIF_MAKSURA,
            SPACE, ALIF, LAM, MEEM, JEEM, HA, WAW, LAM)),

    PASSIVE_PARTICIPLE_MASCULINE(getWord(ALIF_HAMZA_BELOW, SEEN, MEEM, SPACE,
            MEEM, FA, AIN, WAW, LAM, SPACE, MEEM, THAL, KAF, RA)),

    PASSIVE_PARTICIPLE_FEMININE(getWord(ALIF_HAMZA_BELOW, SEEN, MEEM, SPACE,
            MEEM, FA, AIN, WAW, LAM, SPACE, MEEM, WAW_HAMZA_ABOVE, NOON, THA)),

    IMPERATIVE(getWord(ALIF_HAMZA_ABOVE, MEEM, RA)),

    FORBIDDING(getWord(NOON, HA, YA)),

    NOUN_OF_PLACE_AND_TIME(getWord(DTHA, RA, FA));

    private final String value;
    private final ArabicWord label;

    /**
     * @param label
     */
    SarfTermType(ArabicWord label) {
        this.label = label;
        this.value = getLabel() == null ? null : getLabel().toBuckWalter();
    }

    public static SarfTermType fromValue(String v) {
        for (SarfTermType c : SarfTermType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public ArabicWord getLabel() {
        return label;
    }

    public String value() {
        return value;
    }

}
